name: Rust

on:
  - push
  - pull_request
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Load OpenCL
      run: |
        wget -qO - https://repositories.intel.com/graphics/intel-graphics.key |
          sudo apt-key add -
        sudo add-apt-repository \
          'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main'
        sudo apt-get update
        sudo apt-get install \
          intel-opencl-icd \
          intel-level-zero-gpu level-zero \
          intel-media-va-driver-non-free libmfx1
        sudo apt-get install ocl-icd-opencl-dev
    - uses: actions/checkout@v3

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.9.2
        run_install: |
          - recursive: true
            args: [--frozen-lockfile, --strict-peer-dependencies]
          - args: [--global, gulp, prettier, typescript]
          
    - name: Install dependencies
      run: pnpm install

    - name: Run Application
      run: pnpm tauri dev
            
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Load OpenCL
      run: |
        wget -qO - https://repositories.intel.com/graphics/intel-graphics.key |
          sudo apt-key add -
        sudo add-apt-repository \
          'deb [arch=amd64] https://repositories.intel.com/graphics/ubuntu focal main'
        sudo apt-get update
        sudo apt-get install \
          intel-opencl-icd \
          intel-level-zero-gpu level-zero \
          intel-media-va-driver-non-free libmfx1
        sudo apt-get install ocl-icd-opencl-dev
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
