name: Tauri

on:
  push:
  pull_request:
  
jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8.9.2

    - name: Install dependencies
      run: pnpm install

    - name: test stuff
      run: |
        sudo apt install libgtk-3-dev
        sudo apt install libsoup2.4-dev 

    - name: Run Application
      run: pnpm tauri dev
